### ISSUE TITLE
Took -p false doesn not set the passwordgrant: false in .took.yml

### ISSUE THREAD

**Issue by anandchavan** [bserdar/took#18]
`took-insecure add oidc  -c <client id> -k -n <name> -s <secret> -b <callback url> -u <server_url> -p false`

Here is the created profile -

```
  <name>:
    type: oidc-auth
    cfg:
      url: <url>
      tokenapi: ""
      authapi: ""
      form: null
      insecure: true
      profile: ""
      clientid: <client id>
      clientsecret: <secret>
      passwordgrant: true
      callbackurl: <callback url>
```
